version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    ignore:
    - dependency-name: ch.qos.logback:*
      versions:
        - ">= 1.3.0"
    - dependency-name: org.slf4j:*
      versions:
        - ">= 2.0.0"
    - dependency-name: jakarta.activation:jakarta.activation-api
      versions:
        - ">= 2.0.0"
    - dependency-name: jakarta.xml.bind:jakarta.xml.bind-api
      versions:
        - ">= 3.0.0"
    # https://github.com/brettwooldridge/HikariCP/issues/335
    - dependency-name: io.dropwizard.metrics:*
      versions:
        - ">= 4.0.0"
    - dependency-name: io.netty:*
      versions:
        - ">= 5.0.0"
    - dependency-name: org.antlr:stringtemplate
      versions:
        - ">= 4.0.0"
    - dependency-name: org.eclipse.jetty:*
      versions:
        - ">= 10.0.0"
    - dependency-name: org.jruby:*
      versions:
        - ">= 1.8.0"
    - dependency-name: org.ow2.asm:asm
      versions:
        - ">= 6.0.0"
