language: java

sudo: false
cache:
  directories:
      - $HOME/.m2

dist: trusty

before_install:
  - |
    function keep_alive() {
      while true; do
        echo -en "\a"
        sleep 5
      done
    }
    keep_alive &

before_script:
  - jdk_switcher use $JDK

script: mvn -q clean install $PHASE
# Remove --quiet to avoid timeouts
install: mvn -q -U install -DskipTests=true

notifications:
  email:
    - kill-bill-commits@googlegroups.com

matrix:
  include:
    - env: PHASE="-Ptravis-nodb,jdk18" JDK=openjdk8
  fast_finish: true
